# -*- coding: utf-8 -*-
"""강서구 행정동 군집분석

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4ZT607D3Ea_q4-34rN5dlhpSoPmW9Uk
"""

# 한글 설치 후 세션 다시 시작
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("강서구_행정동_통합데이터.csv") # 2020_강서구_데이터셋 참고

df_area = df.copy()
df_area["1인_가구_비율"] = df_area["1인 가구수"] / df_area["세대수"]
df_area["인구당_쓰레기통"] = df_area["쓰레기통_개수"] / df_area["세대수"]
df_area["음식점당_쓰레기통"] = df_area["쓰레기통_개수"] / df_area["전체점포수"]
df_area["세대당_배출량"] = df_area["쓰레기배출량"] / df_area["세대수"]
df_area["음식점_밀도"] = df_area["전체점포수"] / df_area["면적_km2"]
df_area["쓰레기통_밀도"] = df_area["쓰레기통_개수"] / df_area["면적_km2"]
df_area["배출량_밀도"] = df_area["쓰레기배출량"] / df_area["면적_km2"]
df_area["세대_밀도"] = df_area["세대수"] / df_area["면적_km2"]

features_area = [
    "세대수", "전체점포수", "1인_가구_비율", "인구당_쓰레기통",
    "음식점당_쓰레기통", "세대당_배출량", "음식점_밀도", "쓰레기통_밀도",
    "배출량_밀도", "세대_밀도"
]

X_area = StandardScaler().fit_transform(df_area[features_area])
df_area["클러스터"] = KMeans(n_clusters=3, random_state=42).fit_predict(X_area)

# PCA 시각화
X_pca_area = PCA(n_components=2).fit_transform(X_area)
df_area["PCA1_포함"] = X_pca_area[:, 0]
df_area["PCA2_포함"] = X_pca_area[:, 1]

plt.rc('font', family='NanumBarunGothic')

plt.figure(figsize=(8, 6))

for c in sorted(df_area["클러스터"].unique()):
    cluster_data = df_area[df_area["클러스터"] == c]
    plt.scatter(cluster_data["PCA1_포함"], cluster_data["PCA2_포함"], label=f"클러스터 {c}", s=100, alpha=0.7)

for i in range(len(df_area)):
    plt.text(df_area["PCA1_포함"][i], df_area["PCA2_포함"][i], df_area["행정동"][i],
             fontsize=9, alpha=0.9, ha='center', va='center')

plt.title("강서구 행정동 클러스터링 결과")
plt.xlabel("PCA1")
plt.ylabel("PCA2")
plt.legend()
plt.grid(True)
plt.show()

for cluster in sorted(df_area["클러스터"].unique()):
    print(f"\n클러스터 {cluster} 행정동 목록:")
    print(df_area[df_area["클러스터"] == cluster]["행정동"].values)

# 클러스터별 평균값 비교
cluster_summary = df_area.groupby("클러스터")[[
    "세대수", "전체점포수", "1인_가구_비율", "인구당_쓰레기통",
    "음식점당_쓰레기통", "세대당_배출량", "음식점_밀도",
    "쓰레기통_밀도", "배출량_밀도", "세대_밀도"
]].mean().round(2)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# 시각화
plt.figure(figsize=(12, 6))
sns.heatmap(cluster_summary, annot=True, cmap="YlGnBu", fmt=".2f")
plt.title("클러스터별 평균값 비교")
plt.yticks(rotation=0)
plt.show()

"""세대 밀도, 배출량 밀도, 음식점 밀도 가장 높은 클러스터1 선정"""